name: HQGlobalMesh
options:
  bundleIdPrefix: com.hq.global
targets:
  HQGlobalMesh:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - path: Core
      - path: Models
      - path: Resources
      - path: Services
      - path: UI
      - path: ViewModels
      - path: Views
      - path: HQApp.swift
      - path: ContentView.swift
    settings:
      base:
        INFOPLIST_FILE: Info.plist
        GENERATE_INFOPLIST_FILE: YES
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ENABLE_BITCODE: NO
    dependencies:
      - sdk: AVFoundation.framework
      - sdk: MultipeerConnectivity.framework
      - package: Firebase
    
packages:
  Firebase:
    url: https://github.com/firebase/firebase-ios-sdk.git
    from: 10.0.0
