name: HQGlobalMesh
options:
  bundleIdPrefix: com.hq.global
targets:
  HQGlobalMesh:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - path: Core
      - path: Models
      - path: Resources
      - path: Services
      - path: UI
      - path: ViewModels
      - path: Views
      - path: HQApp.swift
      - path: GoogleService-Info.plist
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        SWIFT_VERSION: 5.9
        CODE_SIGNING_ALLOWED: NO
        CODE_SIGNING_REQUIRED: NO
    dependencies:
      - package: Firebase
    
packages:
  Firebase:
    url: https://github.com/firebase/firebase-ios-sdk.git
    from: 10.0.0
